modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="kobe"
version="${mod_version}"

# --- PUBLIC NAME (WHAT PLAYERS SEE) ---
displayName="Economy Shop"

# --- OPTIONAL BUT RECOMMENDED ---
#displayURL="https://modrinth.com/mod/economy-shop"
#logoFile="icon.png"

authors="${mod_authors}"

description='''A clean, modern economy shop system featuring
tiled UI menus, category browsing, buy/sell pricing,
server-side player balances, persistent storage,
and smooth NeoForge integration.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.kobe]]
modId="curios"
mandatory=true
versionRange="[9.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.kobe]]
modId="attributefix"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.kobe]]
modId="geckolib"
mandatory=true
versionRange="[4.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.kobe]]
modId="attributefix"
mandatory=true
versionRange="[21.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.kobe]]
modId="bookshelf"
mandatory=true
versionRange="[21.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.kobe]]
modId="prickle"
mandatory=true
versionRange="[21.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
